[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
extend-select = ["B", "W", "C"]
ignore = ["C400", "C401"]

[project]
name = "ltr_license_scraper_portland_maine"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.10"
license = { "file" = "LICENSE" }
authors = [{ "name" = "bmos", "email" = "wil.t.dsa@pm.me" }]
urls = { "GitHub" = "https://github.com/MaineDSA/ltr_license_scraper_portland" }
dependencies = [
    "pandas==2.2.3",
    "requests==2.32.3",
    "tqdm==4.66.5",
]

[project.optional-dependencies]
dev = [
    "mypy==1.13.0",
    "pandas-stubs==2.2.3.241009",
    "pre-commit==4.0.1",
    "ruff==0.7.2",
    "types-requests==2.32.0.20241016",
    "types-tqdm==4.66.0.20240417"
]
github-actions = [
    "ruff==0.7.2",
    "ydiff==1.3"
]
